# Python CircleCI 2.0 configuration file
#
# Check httpscircleci.comdocs2.0language-python for more details
#
version 2
jobs
  build
    docker
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image circlecipython3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at httpscircleci.comdocs2.0circleci-images
      # - image circlecipostgres9.4

    working_directory ~repo

    steps
      - checkout

      # Download and cache dependencies
      - restore_cache
          keys
          - v1-dependencies-{{ checksum requirements.txt }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run
          name install dependencies
          command 
            python3 -m venv venv
            . venvbinactivate
            pip install -r requirements.txt

      - save_cache
          paths
            - .venv
          key v1-dependencies-{{ checksum requirements.txt }}
        
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # httpspytest.org
      # httpsnose.readthedocs.io
      - run
          name run tests
          command 
            . venvbinactivate
            python manage.py test

      - store_artifacts
          path test-reports
          destination test-reports
          